# Generated by Django 5.2.8 on 2025-11-28 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'db_table': 'days',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='routines.day')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'db_table': 'blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routines',
                'db_table': 'routines',
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('repetitions', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tempo', models.CharField(blank=True, max_length=50, null=True)),
                ('rest_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='routines.block')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Routine Exercise',
                'verbose_name_plural': 'Routine Exercises',
                'db_table': 'routine_exercises',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='routines.routine')),
            ],
            options={
                'verbose_name': 'Week',
                'verbose_name_plural': 'Weeks',
                'db_table': 'weeks',
                'ordering': ['week_number'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='routines.week'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['day'], name='blocks_day_id_499555_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['order'], name='blocks_order_a6ea7f_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['name'], name='routines_name_e6ff1a_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['created_by'], name='routines_created_293f95_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['is_active'], name='routines_is_acti_e7ce09_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexercise',
            index=models.Index(fields=['block'], name='routine_exe_block_i_26e4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexercise',
            index=models.Index(fields=['exercise'], name='routine_exe_exercis_d157ed_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexercise',
            index=models.Index(fields=['order'], name='routine_exe_order_af4480_idx'),
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['routine'], name='weeks_routine_ea24a8_idx'),
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['week_number'], name='weeks_week_nu_8f9564_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('routine', 'week_number')},
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['week'], name='days_week_id_c74ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['day_number'], name='days_day_num_7d9122_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('week', 'day_number')},
        ),
    ]
