# Generated by Django 5.2.8 on 2025-11-26 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('movement_type', models.CharField(blank=True, choices=[('push', 'Push'), ('pull', 'Pull'), ('squat', 'Squat'), ('hinge', 'Hinge'), ('carry', 'Carry'), ('other', 'Other')], max_length=20, null=True)),
                ('primary_muscle_group', models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('full_body', 'Full Body'), ('other', 'Other')], db_index=True, max_length=20, null=True)),
                ('secondary_muscle_groups', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(blank=True, choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('cable', 'Cable'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('kettlebell', 'Kettlebell'), ('other', 'Other')], db_index=True, max_length=20, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercises',
                'indexes': [models.Index(fields=['name'], name='exercises_name_26c749_idx'), models.Index(fields=['primary_muscle_group'], name='exercises_primary_c74680_idx'), models.Index(fields=['equipment'], name='exercises_equipme_0bc618_idx'), models.Index(fields=['difficulty'], name='exercises_difficu_bf8baf_idx'), models.Index(fields=['is_active'], name='exercises_is_acti_9a5544_idx')],
            },
        ),
    ]
