# Generated by Django 6.0 on 2025-12-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='session',
            new_name='training_se_user_id_3c8781_idx',
            old_name='sessions_user_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='training_se_routine_ef6d49_idx',
            old_name='sessions_routine_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='training_se_date_0f8b9b_idx',
            old_name='sessions_date_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='training_se_energy__d2721d_idx',
            old_name='sessions_energy_level_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionexercise',
            new_name='session_exe_session_7076b1_idx',
            old_name='session_exercises_session_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionexercise',
            new_name='session_exe_exercis_473c1a_idx',
            old_name='session_exercises_exercise_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionexercise',
            new_name='session_exe_order_c0a58f_idx',
            old_name='session_exercises_order_idx',
        ),
    ]
